(function(root){
 'use strict';
 const empty=()=>({componentCounter:0,tubingCounter:0,components:[],connections:[],tubingConnections:[]});
 function validate(value,library){
  const fail=()=>{throw Error('El archivo contiene un proyecto inválido o incompatible.');};
  if(!value||value.format!=='taller-visual-v1'||typeof value.name!=='string'||!value.name.trim()||value.name.length>100||typeof value.notes!=='string'||value.notes.length>5000)fail();
  const s=value.state;if(!s||!Array.isArray(s.components)||s.components.length>200||!Array.isArray(s.connections)||s.connections.length>500||!Array.isArray(s.tubingConnections)||s.tubingConnections.length>500)fail();
  const out=empty(),ids=new Map();
  for(const c of s.components){if(!c||typeof c.id!=='string'||!/^\d{1,8}$/.test(c.id)||ids.has(c.id)||!Object.hasOwn(library,c.type)||![c.left,c.top,c.rotation].every(Number.isFinite)||Math.abs(c.left)>100000||Math.abs(c.top)>100000||Math.abs(c.rotation)>36000)fail();const base=library[c.type];if(base.views&&!Object.hasOwn(base.views,c.view))fail();if(!base.views&&c.view!==null&&c.view!==undefined)fail();const definition=base.views?{...base,...base.views[c.view]}:base;ids.set(c.id,definition);out.components.push({id:c.id,type:c.type,left:c.left,top:c.top,rotation:c.rotation,view:c.view||null});out.componentCounter=Math.max(out.componentCounter,Number(c.id));}
  const used=new Set(),tubeIds=new Set();
  function edge(e,tube){if(!e||(e.aId===e.bId&&e.aPortId===e.bPortId))fail();const a=ids.get(e.aId)?.ports.find(p=>p.id===e.aPortId),b=ids.get(e.bId)?.ports.find(p=>p.id===e.bPortId);if(!a||!b)fail();const ak=e.aId+':'+e.aPortId,bk=e.bId+':'+e.bPortId;if(used.has(ak)||used.has(bk))fail();const ac=a.connection,bc=b.connection;if(ac.size!==bc.size)fail();if(tube){if(ac.family!=='tube'||bc.family!=='tube'||ac.role!=='tube-fitting'||bc.role!=='tube-fitting'||e.size!==ac.size||!['straight','45','90'].includes(e.shape)||typeof e.id!=='string'||!/^tube-\d{1,8}$/.test(e.id)||tubeIds.has(e.id)||e.material!=='316SS'||![e.legA,e.legB].every(x=>Number.isFinite(x)&&x>=0&&x<=10000))fail();tubeIds.add(e.id);out.tubingCounter=Math.max(out.tubingCounter,Number(e.id.slice(5)));}else if(ac.family!=='thread'||bc.family!=='thread'||ac.standard!==bc.standard||!['male','female'].includes(ac.gender)||!['male','female'].includes(bc.gender)||ac.gender===bc.gender)fail();used.add(ak);used.add(bk);const clean={aId:e.aId,aPortId:e.aPortId,bId:e.bId,bPortId:e.bPortId};return tube?{...clean,id:e.id,size:e.size,material:e.material,shape:e.shape,legA:e.legA,legB:e.legB}:clean;}
  out.connections=s.connections.map(e=>edge(e,false));out.tubingConnections=s.tubingConnections.map(e=>edge(e,true));
  return {format:'taller-visual-v1',id:typeof value.id==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(value.id)?value.id:null,name:value.name.trim(),notes:value.notes,state:out};
 }
 function materials(state,library){const rows=[];for(const c of state.components){let row=rows.find(r=>r.key===c.type);if(row){row.quantity++;continue;}const d=library[c.type];rows.push({key:c.type,name:d.name,reference:d.name,detail:d.connectionLabel||'Según configuración del catálogo de trabajo',image:d.image||d.views?.[d.defaultView]?.image||'',quantity:1});}for(const t of state.tubingConnections){const key='tube-'+t.size+'-'+t.shape;let row=rows.find(r=>r.key===key);if(row){row.quantity++;continue;}rows.push({key,name:'Tramo de tubo',reference:'Por especificar',detail:`${t.size} in OD · 316SS · ${t.shape==='straight'?'recto':t.shape+'°'}`,image:'',quantity:1});}return rows;}
 function csv(rows){const cell=x=>'"'+String(x).replace(/^[=+@-]/,m=>"'"+m).replaceAll('"','""')+'"';return '\ufeff'+[['Componente','Referencia / familia','Detalle','Cantidad'],...rows.map(r=>[r.name,r.reference,r.detail,r.quantity])].map(r=>r.map(cell).join(';')).join('\r\n');}
 root.WorkshopData={empty,validate,materials,csv};
})(typeof module==='object'?module.exports:globalThis);
